name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run setup
      uses: ./.github/actions/setup

    - name: Run tests
      run: |
          printf "TEXTBELT_API_KEY=${{ secrets.TEXTBELT_API_KEY }}\nTEST_PHONE_NUMBER=${{ secrets.TEST_PHONE_NUMBER }}" > tests/.env.test
          make test
          rm tests/.env.test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
